# Generated by Django 3.2.7 on 2021-09-26 20:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=15, verbose_name='Nome: ')),
                ('ano_letivo', models.IntegerField(max_length=4, verbose_name='Ano letivo: ')),
            ],
        ),
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('numero_chamada', models.IntegerField(max_length=99, verbose_name='Número chamada: ')),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.turma')),
            ],
        ),
    ]
